# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: push.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'push.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npush.proto\"&\n\x07SubItem\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x03(\t\"R\n\x06\x43\x32SMsg\x12\x0b\n\x03\x61\x63t\x18\x01 \x01(\t\x12\x0f\n\x07hbValue\x18\x02 \x01(\x03\x12\x17\n\x05items\x18\x03 \x03(\x0b\x32\x08.SubItem\x12\x11\n\trequestid\x18\x04 \x01(\t\"E\n\x06\x45rrMsg\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x03\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\r\n\x05topic\x18\x03 \x01(\t\x12\x11\n\trequestid\x18\x04 \x01(\t\"Z\n\nSubRepItem\x12\r\n\x05topic\x18\x01 \x01(\t\x12\r\n\x05scode\x18\x02 \x03(\t\x12\r\n\x05\x66\x63ode\x18\x03 \x03(\t\x12\x0f\n\x07invalid\x18\x04 \x03(\t\x12\x0e\n\x06\x64\x65nied\x18\x05 \x03(\t\"%\n\x08TopicMsg\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\xbf\x01\n\x06S2CMsg\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07hbValue\x18\x02 \x01(\x03\x12\x17\n\x06\x65rrMsg\x18\x03 \x01(\x0b\x32\x07.ErrMsg\x12\x18\n\x05items\x18\x04 \x03(\x0b\x32\t.TopicMsg\x12\x0c\n\x04time\x18\x05 \x01(\x03\x12\x11\n\trequestid\x18\x06 \x01(\t\x12\x1b\n\x06subRep\x18\x07 \x03(\x0b\x32\x0b.SubRepItem\x12\t\n\x01t\x18\x08 \x01(\x03\x12\r\n\x05\x63\x61\x63he\x18\t \x01(\x03\x12\n\n\x02id\x18\n \x01(\x03\x42\x0bZ\t./;pushpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'push_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\t./;pushpb'
  _globals['_SUBITEM']._serialized_start=14
  _globals['_SUBITEM']._serialized_end=52
  _globals['_C2SMSG']._serialized_start=54
  _globals['_C2SMSG']._serialized_end=136
  _globals['_ERRMSG']._serialized_start=138
  _globals['_ERRMSG']._serialized_end=207
  _globals['_SUBREPITEM']._serialized_start=209
  _globals['_SUBREPITEM']._serialized_end=299
  _globals['_TOPICMSG']._serialized_start=301
  _globals['_TOPICMSG']._serialized_end=338
  _globals['_S2CMSG']._serialized_start=341
  _globals['_S2CMSG']._serialized_end=532
# @@protoc_insertion_point(module_scope)
